### ISSUE TITLE
add retrieve and rank

### ISSUE THREAD

**Issue by vnordin** [watson-developer-cloud/simple-chat-objective-c#1]
Hi,

I'm looking for an enhanced version of this app, which btw is really nice!! I want to include Retrieve & Rank in this app, so when Conversation is not able to answer, I want R&R to kick in.. Does someone know if this has been done before in another project similiar to this? I know there is the Conversation-enhanced app, but I would really like to use this iOs-app with STT and TTS.

Thank you!!

**Comment by germanattanasio** [comment]
HI @vnordin I don't think we are going to add Retrieve and Rank. It's not part of the idea behind this app. Thanks for the suggestion!
