### ISSUE TITLE
The project simply cannot run!

### ISSUE THREAD

**Issue by Buliceli** [watson-developer-cloud/simple-chat-objective-c#4]
1.Clone the repository: git clone https://github.com/watson-developer-cloud/simple-chat-objective-c.git
2.Build the dependencies: carthage update --platform iOS
3.Open ChatApp.xcworkspace

4.Update your service credentials in Credentials.swift
Build and run the app!
The first three steps are carried out. How do you do the fourth step? Thank you!

**Comment by glennrfisher** [comment]
Hi @Buliceli. Sorry for the confusion. The project already includes a `CredentialsExample.swift` file. I just added an extra step to the readme to make it a bit clearer that `CredentialsExample.swift` should be copied to `Credentials.swift` then updated with the service credentials.
