### ISSUE TITLE
Watson Error

### ISSUE THREAD

**Issue by Buliceli** [watson-developer-cloud/simple-chat-objective-c#6]
Run successfully popups prompt: The operation could't be completed.Resource not found

**Comment by glennrfisher** [comment]
Hi @Buliceli. I'm afraid you'll need to provide more information. I followed the getting started steps and did not run into this issue when running on the simulator of my iPhone.

"Resource not found" messages tend to be from frameworks that are not copied into the application. Are you sure you ran `carthage update --platform iOS`? I assume you didn't delete the run script build phase that copies the frameworks?
